server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    root /var/www/cloud_notes/nav;
    index index.html;

    location = / {
        try_files /index.html =404;
    }

    location / {
        return 404;
    }
}

server {
    listen 1872;
    listen [::]:1872;
    server_name _;

    root /opt/cloud_notes/app/frontend/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
